iree-compile base_ir/vae_decode.mlir \
    --iree-vulkan-target-triple=rdna3-unknown-linux \
    --iree-llvmcpu-target-triple=x86_64-unknown-linux \
    --iree-hal-cuda-llvm-target-arch=sm_80 \
    --iree-rocm-target-chip=gfx942 \
    --iree-hal-target-backends=rocm \
    --iree-global-opt-propagate-transposes=true \
    --iree-global-opt-only-sink-transposes=true \
    --iree-opt-outer-dim-concat=true \
    --iree-rocm-link-bc=true \
    --iree-codegen-llvmgpu-use-vector-distribution \
    --iree-rocm-bc-dir=/opt/rocm/amdgcn/bitcode \
    --iree-execution-model=async-external \
    --iree-opt-splat-parameter-archive-export-file=tmp/vae.irpa \
    --iree-preprocessing-pass-pipeline="builtin.module(iree-preprocessing-transpose-convolution-pipeline)" \
    --iree-codegen-transform-dialect-library=specs/attention_and_matmul_spec.mlir \
    --mlir-disable-threading \
    -o tmp/unet.vmfb
